spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
